#cloud-config
hostname: ${hostname}

disable_root: true
ssh_pwauth: true

users:
  - name: ${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_key}

chpasswd:
  list: |
    ${username}:ubuntu
  expire: false

package_update: true
packages:
  - qemu-guest-agent

runcmd:
  - systemctl enable --now qemu-guest-agent
